dags:
  gitSync:
    enabled: true
    repo: "git@github.com:wittycodes/demostack.git"
    branch: main
    subPath: "workflows"
    sshKeySecret: airflow-ssh-secret
extraSecrets:
  airflow-ssh-secret:
    data: |
      gitSshKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCTUZ6bzhFRkN0UmEvcjRJeXYyV29nZy9ZRitTakt4dzFENGllaVpnVlpLQUFBQUtBN05iNkJPelcrCmdRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQk1Gem84RUZDdFJhL3I0SXl2MldvZ2cvWUYrU2pLeHcxRDRpZWlaZ1ZaS0EKQUFBRURDZ0gwWHFaMlZwelY0Wm5OdE5aR3BhSy9TSjV1cEcxVzB4cmkxdmdTbjQwd1hPandRVUsxRnIrdmdqSy9aYWlDRAo5Z1g1S01ySERVUGlKNkptQlZrb0FBQUFHSEJuWVhKbkxtOW1abWxqYVdGc1FHZHRZV2xzTG1OdmJRRUNBd1FGCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
extraEnv: |
  - name: AIRFLOW__API__AUTH_BACKENDS
    value: airflow.api.auth.backend.basic_auth