apiVersion: v1
kind: Secret
metadata:
  name: airflow-basicauth-secret
type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: admin # required field for kubernetes.io/basic-auth
