apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: my-alertmanager-config
spec:
  global:
    # ... other global config
  receivers:
  - name: 'pod_memory_analysis'
    webhookConfigs:
    - url: 'http://your-webhook-endpoint:port/path'
      # Add optional headers, httpConfig, sendResolved, etc.
  route:
    receiver: 'default'
#    group_by: [ 'alertname' ]
#    group_wait: 5m
#    group_interval: 5m
#    repeat_interval: 1h
    routes:
      - match_label:
          airflow_dag_id: pod_memory_analysis
        receiver: pod_memory_analysis
      - match_label:
          airflow_dag_id: pod_volume_analysis
        receiver: pod_volume_analysis

