apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: custom-alerts-config
  namespace: prometheus
  labels:
    release: poc-stack

spec:
#  global:
#    # ... other global config
  receivers:
  - name: 'airflow_webhook'
    webhookConfigs:
    - url: 'http://poc-stack-webserver.airflow.svc.cluster.local:8080/webhooks/prometheus'
  route:
    receiver: 'airflow_webhook'
    groupBy: [ 'alertname' ]
    groupWait: 5s
#    groupInterval: 30s
    repeatInterval: 2m



