apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-service-account
  namespace: airflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-clusterrole
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: airflow-service-account
  namespace: airflow  # Replace with the namespace where the service account exists
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: airflow-clusterrole
